const data = {
  'Aaron Smith': [
    {
      week: 7,
      day: 3,
      id: 123457,
      type: 'PICK UP',
      start_time: 15,
      end_time: 19,
      location: 'Dollarama',
    },
    {
      week: 11,
      day: 7,
      id: 123461,
      type: 'DROP OFF',
      start_time: 11,
      end_time: 12,
      location: 'Home Depot',
    },
    {
      week: 14,
      day: 5,
      id: 123470,
      type: 'OTHER ',
      start_time: 13,
      end_time: 17,
      location: 'Sobeys',
    },
    {
      week: 34,
      day: 5,
      id: 123489,
      type: 'PICK UP',
      start_time: 15,
      end_time: 19,
      location: 'Staples',
    },
    {
      week: 35,
      day: 2,
      id: 123479,
      type: 'PICK UP',
      start_time: 13,
      end_time: 16,
      location: 'Atlantic Superstore',
    },
    {
      week: 37,
      day: 4,
      id: 123468,
      type: 'DROP OFF',
      start_time: 10,
      end_time: 11,
      location: 'Best Buy',
    },
    {
      week: 40,
      day: 3,
      id: 123474,
      type: 'DROP OFF',
      start_time: 17,
      end_time: 20,
      location: 'Walmart',
    },
    {
      week: 43,
      day: 4,
      id: 123485,
      type: 'OTHER ',
      start_time: 16,
      end_time: 18,
      location: 'PetSmart',
    },
    {
      week: 44,
      day: 4,
      id: 123459,
      type: 'OTHER ',
      start_time: 9,
      end_time: 13,
      location: 'Home Depot',
    },
    {
      week: 49,
      day: 2,
      id: 123462,
      type: 'PICK UP',
      start_time: 9,
      end_time: 12,
      location: 'Best Buy',
    },
    {
      week: 49,
      day: 2,
      id: 123472,
      type: 'PICK UP',
      start_time: 17,
      end_time: 20,
      location: 'Costco',
    },
    {
      week: 52,
      day: 5,
      id: 123467,
      type: 'DROP OFF',
      start_time: 13,
      end_time: 14,
      location: 'Home Depot',
    },
  ],
  'Fierce Bob': [
    {
      week: 4,
      day: 6,
      id: 123480,
      type: 'DROP OFF',
      start_time: 17,
      end_time: 21,
      location: 'Staples',
    },
    {
      week: 7,
      day: 3,
      id: 123487,
      type: 'DROP OFF',
      start_time: 12,
      end_time: 14,
      location: 'Sobeys',
    },
    {
      week: 10,
      day: 6,
      id: 123477,
      type: 'OTHER ',
      start_time: 8,
      end_time: 10,
      location: 'Sobeys',
    },
    {
      week: 19,
      day: 2,
      id: 123490,
      type: 'DROP OFF',
      start_time: 15,
      end_time: 18,
      location: 'Canadian Tire',
    },
    {
      week: 22,
      day: 1,
      id: 123484,
      type: 'DROP OFF',
      start_time: 17,
      end_time: 21,
      location: 'Atlantic Superstore',
    },
    {
      week: 23,
      day: 1,
      id: 123476,
      type: 'OTHER ',
      start_time: 8,
      end_time: 11,
      location: 'Best Buy',
    },
    {
      week: 30,
      day: 4,
      id: 123465,
      type: 'PICK UP',
      start_time: 8,
      end_time: 12,
      location: 'Walmart',
    },
    {
      week: 31,
      day: 6,
      id: 123475,
      type: 'PICK UP',
      start_time: 17,
      end_time: 18,
      location: 'Best Buy',
    },
    {
      week: 42,
      day: 2,
      id: 123486,
      type: 'DROP OFF',
      start_time: 10,
      end_time: 11,
      location: 'Rona',
    },
    {
      week: 42,
      day: 4,
      id: 123481,
      type: 'PICK UP',
      start_time: 13,
      end_time: 16,
      location: 'Canadian Tire',
    },
  ],
  'John Doe': [
    {
      week: 2,
      day: 7,
      id: 123491,
      type: 'OTHER ',
      start_time: 14,
      end_time: 16,
      location: 'Staples',
    },
    {
      week: 11,
      day: 5,
      id: 123482,
      type: 'DROP OFF',
      start_time: 12,
      end_time: 13,
      location: 'Canadian Tire',
    },
    {
      week: 11,
      day: 6,
      id: 123460,
      type: 'OTHER ',
      start_time: 11,
      end_time: 15,
      location: 'Shoppers Drug Mart',
    },
    {
      week: 14,
      day: 2,
      id: 123464,
      type: 'OTHER ',
      start_time: 17,
      end_time: 18,
      location: 'Staples',
    },
    {
      week: 17,
      day: 1,
      id: 123471,
      type: 'OTHER ',
      start_time: 12,
      end_time: 14,
      location: 'Best Buy',
    },
    {
      week: 21,
      day: 2,
      id: 123473,
      type: 'OTHER ',
      start_time: 12,
      end_time: 15,
      location: 'Dollarama',
    },
    {
      week: 22,
      day: 4,
      id: 123456,
      type: 'OTHER ',
      start_time: 11,
      end_time: 13,
      location: 'Walmart',
    },
    {
      week: 24,
      day: 6,
      id: 123463,
      type: 'PICK UP',
      start_time: 10,
      end_time: 14,
      location: 'Best Buy',
    },
    {
      week: 29,
      day: 4,
      id: 123488,
      type: 'PICK UP',
      start_time: 17,
      end_time: 18,
      location: 'Staples',
    },
    {
      week: 33,
      day: 7,
      id: 123458,
      type: 'DROP OFF',
      start_time: 15,
      end_time: 16,
      location: 'Best Buy',
    },
    {
      week: 39,
      day: 1,
      id: 123493,
      type: 'PICK UP',
      start_time: 16,
      end_time: 17,
      location: 'Shoppers Drug Mart',
    },
    {
      week: 44,
      day: 1,
      id: 123478,
      type: 'PICK UP',
      start_time: 10,
      end_time: 13,
      location: 'PetSmart',
    },
    {
      week: 44,
      day: 1,
      id: 123483,
      type: 'PICK UP',
      start_time: 13,
      end_time: 17,
      location: 'Dollarama',
    },
    {
      week: 45,
      day: 1,
      id: 123469,
      type: 'DROP OFF',
      start_time: 9,
      end_time: 10,
      location: 'Costco',
    },
    {
      week: 48,
      day: 2,
      id: 123466,
      type: 'DROP OFF',
      start_time: 17,
      end_time: 19,
      location: 'Rona',
    },
    {
      week: 52,
      day: 2,
      id: 123492,
      type: 'DROP OFF',
      start_time: 13,
      end_time: 14,
      location: 'Rona',
    },
  ],
};

const convert = (data) => {
  const result = {};
  for (let [driver, dataArr] of Object.entries(data)) {
    result[driver] = {};

    dataArr.forEach((obj) => {
      if (!result[driver][obj.week]) {
        result[driver][obj.week] = {};
        result[driver][obj.week][obj.day] = {};
        result[driver][obj.week][obj.day]['tasks'] = [];
        result[driver][obj.week][obj.day].tasks.push({
          id: obj.id,
          type: obj.type,
          start_time: obj.start_time,
          end_time: obj.end_time,
          location: obj.location,
        });
      } else {
        if (!result[driver][obj.week][obj.day]) {
          result[driver][obj.week][obj.day] = {};
          result[driver][obj.week][obj.day]['tasks'] = [];
          result[driver][obj.week][obj.day].tasks.push({
            id: obj.id,
            type: obj.type,
            start_time: obj.start_time,
            end_time: obj.end_time,
            location: obj.location,
          });
        } else {
          result[driver][obj.week][obj.day].tasks.push({
            id: obj.id,
            type: obj.type,
            start_time: obj.start_time,
            end_time: obj.end_time,
            location: obj.location,
          });
        }
      }
    });
  }

  return result;
};

console.log(convert(data));
